### ISSUE TITLE
Restart in-progress workflow instance and auto-load previously-entered data if spec has been modified.

### ISSUE THREAD

**Issue by ajlouie** [sartography/cr-connect-workflow#10]
When a study has a workflow that is already in progress and the workflow spec is changed, save the data that has already been entered and restart the workflow.

Version workflow specs and save the version of the spec that the study is using.

**Comment by danfunk** [comment]
The workflow will now continue using the original specification, but it can be soft-reset (use the new workflow specification, with the original serialized process) which can be useful for text and minor form changes, and some structural changes if they are in the future for the workflow, and a hard-reset which will preserve the data from the last executed task, but drop the history and progress, requiring users to start from the beginning.
