### ISSUE TITLE
Unnamed tasks throw errors

### ISSUE THREAD

**Issue by danfunk** [sartography/cr-connect-workflow#139]
If a task doesnt not have a name,  we get this when trying to build the navigation list. Resutling in an error when running the workflow but no error in validation, and no message to deal with.

File "/app/crc/api/workflow.py", line 151, in get_workflow
    workflow_api_model = __get_workflow_api_model(processor)
  File "/app/crc/api/workflow.py", line 110, in __get_workflow_api_model
    if ' ' in nav_item['title']:

**Comment by cullerton** [comment]
@danfunk 

I can't reproduce this error.

I made a couple different workflows each with at least one task that didn't have a name. All pass the shield test. All run as workflows, navigation and everything.

I think we're mixing apples and oranges here.
**What is nav_item['title']?**
Does it come from the database? I don't think it's looking at the bpmn file.

Do you still see this error happen?

(BTW, the code referenced above doesn't even exist any more. We now call WorkflowService.processor_to_workflow_api(processor).)

**Comment by cullerton** [comment]
This appears to work now on testing.
I have a workflow containing multiple tasks with no name.
It runs, and the navigation seems correct to me.

https://testing.crconnect.uvadcos.io/app/workflow/14255/task/ed921d3b-dda9-424c-b75b-75bd35b7cf83
