### ISSUE TITLE
When only one .bpmn file is available in a Workflow Specification, make it the default automatically.

### ISSUE THREAD

**Issue by danfunk** [sartography/cr-connect-workflow#142]
The first bpmn added to a workflow should automatically be marked as the primary workflow.   Currently the Configurator too often creates the bpmn, adds tasks and then clicks on the shield to see if the workflow is correct at which time they receive an error that no default workflow has been set.

**Comment by calexh-sar** [comment]
Working as designed for creating a bpmn, but not when uploading one.  Will write new ticket for that use case.
