### ISSUE TITLE
Shield Check - Form Field Type not specified

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect-workflow#143]
The shield check does not catch if the Form Field Type is not specified.

**Comment by cullerton** [comment]
Not sure what changes I need to make to this ticket other than moving to the Review/QA column.

**Comment by calexh-sar** [comment]
@cullerton is it possible to get the name of the field that is missing the Type?

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/56a3a381-c97b-4e21-bbb4-4197d21dc817)

**Comment by cullerton** [comment]
Add task for Alex too.

Side Note: this error isn't sent to Sentry (at least, not  correctly).

**Comment by calexh-sar** [comment]
Working as designed.
