### ISSUE TITLE
Infinite Validations! Don't do it!

### ISSUE THREAD

**Issue by danfunk** [sartography/cr-connect-workflow#262]
Imagine a workflow where you check to see if the a Department Chair exists, and if it does not, you present a page explaining that they need to go back to the protocol builder and add it.  Then the workflow directs you back to a previous task.

Now imagine that we have test data in our StudyInfo Script tasks' validate only that does not specify a Department Chair.

In this case, when the validate button is clicked, the validation script will step through the workflow, attempting to test each task in turn.  But it always ends up going down the same path, which doesn't dead end, it loops.

So validation just goes on and on and on and on and on and on and on and on and on and on and on and on and on and on and on and on. 

We need some sensible limit on our validation process, so it can say "hey, I have processed a 1000 tasks, and I never get to an end task" or "I've processed the same exact task spec over 20 times", and then returns a validation error saying "Looks like this workflow is looping, and the validation process got trapped in that loop.  So validation was terminated.  Your workflow may be fine, but we can't test it effectively because we aren't able to break out of a loop in your workflow process. 

**ALSO:**  This example really happened.  We should make sure that the example data returned from the study info script includes a valid department chair.  As it's going to be a reuirement that we get back a valid value for both the PI and the Department Chair

**Comment by cullerton** [comment]
How did this go from "Imagine a workflow..." to Mike having a new ticket?

**Comment by calexh-sar** [comment]
@cullerton pls let me know when you have some time to discuss this ticket.

**Comment by calexh-sar** [comment]
@cullerton would you pls remind me what, if any, work you did on this ticket.  Trying to figure out if there is anything to test.

**Comment by cullerton** [comment]
@calexh-sar We added a check during validation.
If validation tries something more than 100 times, we send a message like
`There appears to be an infinite loop in the validation. Task is blah`

**Comment by calexh-sar** [comment]
Got the error message.  Still don't like the state we are in for this.  Hope we come up with something better in the future.  But for now, working as designed.

**Comment by cullerton** [comment]
I like this solution for workflows where someone has an actual infinite loop error.
It's not the best solution for your other issue in ticket 312 though
