### ISSUE TITLE
Jinja INCLUDE to create complex templates

### ISSUE THREAD

**Issue by danfunk** [sartography/cr-connect-workflow#403]
Basically, we want the ability to have something like this in the task.data:
name="Dan"
my_template = "Hi {{name}}, This is a jinja template too!"

And then be able to inject this into documentation, emails, etc... like this:

```
Please Introduce yourself.
{% include 'my_template' %} 
Cool Right?
```
Which should produce:
```
Please Introduce yourself.
Hi Dan, This is a jinja template too!
Cool Right?
```

While some quick tests showed this was possible, I think we need to do this right such that:

- [ ] There is a single bit of code / service that handles markdown rendering, so it is consistent throughout the system.
- [ ] This is tested to show it works for Task Documentation (See below)
- [ ] This is tested to show it works for Emails
- [ ] This is tested to show it works for Document Generation

Here is working code that will create a custom jinja environment that will use a dictionary to find templates to use.  This allows us to load the main template, and then any data in the task_data is available with imports.
```
        templates = spiff_task.data
        templates['main_template'] = documentation
        jinja2_env = Environment(loader=DictLoader(templates))

        try:
            template = jinja2_env.get_template('main_template')
            return template.render(**spiff_task.data)
```

Here is a good test for you, that I used when just verifying that this can work.
```
   def test_documentation_processing_handles_imports(self):

        self.load_example_data()
        workflow = self.create_workflow('random_fact')
        processor = WorkflowProcessor(workflow)
        processor.do_engine_steps()

        task = processor.next_task()
        task.data = {"my_template": "Hi {{name}}, This is a jinja template too!",
                     "name": "Dan"}
        task.task_spec.documentation = """{% include 'my_template' %} Cool Right?"""
        docs = WorkflowService._process_documentation(task)
        self.assertEqual("Hi Dan, This is a jinja template too! Cool Right?", docs)

**Comment by cullerton** [comment]
Most of our jinja template stuff looks like
```
template = Template(message)
content = template.render(data)
```
where we have a text template--maybe html, maybe an email, and we use Jinja to add dynamic values to the text.
We have a solution for this.

We can also use a Word document as a template, instead of a text file. We use the complete_template script for this.
This piece is a bit trickier, and I would like to split the complete_template script part into a separate ticket.

This way we can test out the embedded template part of this ticket on Testing to make sure we aren't missing something.
