### ISSUE TITLE
Support BPMN 2.0 subprocesses

### ISSUE THREAD

**Issue by ajlouie** [sartography/cr-connect-workflow#9]
Subprocesses work - potential dupe from some of the more specific things -

i.e. Nav List not working correctly

**Comment by danfunk** [comment]
![image](https://user-images.githubusercontent.com/515662/80520430-69e50c00-8957-11ea-9cfd-a9a5fcf5f53b.png)
IF a name is given to a sub-process, and not just an id, a "process_name" will show up on the task field showing what sub_process it belongs to.  If the main workflow has a name, that name will show up on top level tasks.

**Comment by ajlouie** [comment]
I've created https://github.com/sartography/cr-connect-frontend/issues/68 to track progress on the UI for subprocesses

**Comment by w4kpm** [comment]
this is complete except for the nav list AFAICT

**Comment by danfunk** [comment]
very outdated - and not in line with how we handle navigation at this point.
